name: Publish WinForms Application

on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x' 
          
      - name: Restore dependencies
        run: dotnet restore
        working-directory: .

      - name: Publish application
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true /p:Configuration=Release
        working-directory: ./Passwords_project 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PasswordGenerator-WinForms
          path: passwords_project/bin/Release/net6.0-windows/win-x64/publish/*
          retention-days: 7
